### ISSUE TITLE
DOC, TST: support pylint

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#124]
Works really well out-of-the-box

**Comment by MarcoGorelli** [comment]
I will have to make sure the pylint config file works

**Comment by girip11** [comment]
@MarcoGorelli  Any reason why we name the temporary python file  with three spaces before the `.py` extension?

**Comment by girip11** [comment]
With pylint, I am hitting two issues arising due to nbqa's internal working.

1.  Module name "notebook_with_indented_magics   " doesn't conform to snake_case
2.  unnecessary pass statement

If we can remove the additional spaces introduced in the file name, first issue can be fixed.
Second issue can be fixed, If I use some builtin function like `type()` or `id()`instead of `pass`. `print` is not preferred because of the issue with doctest.

 I am open to ideas

**Comment by MarcoGorelli** [comment]
> @MarcoGorelli Any reason why we name the temporary python file with three spaces before the `.py` extension?

This is so that its name is of the same length as the notebook's name, in case any output uses the length of the file to make some fancy formatting box. Could use `aaa` insead of `   `?

As for `pass` / `print` - you'd suggested conditionally using `print`, depending on the tool which is used. So, `print` for pylint, and `pass` for the rest?

**Comment by girip11** [comment]
Yes I had proposed different statements for different tools. But I am hesitant now to implement that way. I would like nbqa to be tool agnostic as much as possible. If we can avoid such tool dependent options, then we should go for it. What do you think?

**Comment by girip11** [comment]
I used `type` builtin function pylint, flake8. It worked. To be sure I can run it once against all other supported tools.

**Comment by MarcoGorelli** [comment]
Awesome! Thanks for looking into this, if `type()` works well with all the tools we're currently testing then it seems like a winner!

**Comment by girip11** [comment]
I have one other solution. I am trying out that. I will try to send a sample PR in a day or two.

**Comment by girip11** [comment]
PR https://github.com/nbQA-dev/nbQA/pull/302 to complete pylint support.

**Comment by girip11** [comment]
Pylint support added. Closing this issue.
