### ISSUE TITLE
CLN can we not ignore E0401 for pylint?

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#212]
Now that pylint isn't incompatible with the rest of the dependencies, is it OK to remove
```
    "E0401",  # import error: I run pylint in a separate environment so it's OK
```
from pyproject.toml ?

**Comment by s-weigand** [comment]
Try removing it and run `pre-commit run -a`, if it passes it should be fine.

**Comment by girip11** [comment]
If this rule is removed from the pylint conf, we would get import error. **pytest and other import dependencies** in the source/test files won't be available to the pylint module since this would be run in an isolated environment by the pre-commit.  

To fix this issue we have two options.

1. We need to make all our source and test dependencies available to pylint during pre-commit check using the **additional_dependencies** key **.pre-commit-config.yaml** for pylint would look like below. But this rule would keep failing as and when we take dependency on some new other 3rd party package.

```YAML
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        exclude: "docs"
        additional_dependencies:
          - "pytest"
```

2. Alternatively, we can make pylint as a local hook as suggested by creator the pre-commit. This is a generic change. We can freely add new dependencies and no need to change the pre-commit config everytime.

> pre-commit runs pylint from an isolated virtualenv. Many of pylint's checks perform dynamic analysis which will fail there. You may find configuring pylint as a local hook more useful.

I tried making pylint as a local hook with **language: system**. This will make the pylint picked up from our virtual environment or some other local environment based on PATH variable. When we develop, usually we have the virtual environment activated, so pre-commit will have not issue finding and running pylint. In github actions, we need to install all the dependencies for pylint to work under system flag.

3. Don't remove the rule E0401 from pylint configuration.

I could not think of any other alternate solution. I will raising PR. If you folks don't like the PR, feel free to close the PR without merging. [PR](https://github.com/nbQA-dev/nbQA/pull/229)

**Comment by girip11** [comment]
PR merged, so closing this issue
