### ISSUE TITLE
Don't ignore in-line magic (when possible)

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#279]
There are some in-line magics that _could_ be replaced with valid Python. For example
```
from foo import func

if True:
    %time func()
```

will currently get transformed to 
```
from foo import func

if True:
    pass # <comment with hash>
```
meaning that `flake8` would incorrectly warn that `func` is imported but unused.

Not sure how the substitution would work, but I think this would make sense as a longer-term goal

**Comment by girip11** [comment]
The approach I used to solve this issue is to first extract only the python code from the statement. Then parse the python code snippet using ast.parse and check if the python code contains any Call node. I used Call node type since most of the time we either import a function or class. If the python code contains a Call node, I would place the entire code inside the template string "callable(lambda _: {code}) # {token}". Impl can be found here https://github.com/girip11/nbQA/blob/b83aaadb9b6f334a719d00ddc74abd18b396cb6d/nbqa/handle_magics.py#L15

I know this is not the best of approaches. Any suggestions are welcome.

**Comment by girip11** [comment]
But with this approach, we would have issue replacing the statement back to the original statement when tools like pyupgrade, black modify the code.
For example

```Python
from foo import func

if True:
    %time func(arg = 'arg1')
```

After replacing with template becomes

```Python
from foo import func

if True:
    callable(lambda _: func(arg = 'arg1')  # token
```

When black runs on this code, we would get

```Python
from foo import func

if True:
    callable(lambda _: func(arg="arg1")  # token
```

This would affect the `replace_magics` logic, where we just where we currently check exact match assuming the replaced python code does not get altered.

I thought of adding comments to disable black (`#fmt: off`), pyupgrade. But I find this solution very ugly and won't scale on any new tools since nbqa is tool agnostic.

So we would have to find another way to replace the original magic back using some logic rather than just a string equality check.

**Comment by girip11** [comment]
This is addressed by [PR](https://github.com/nbQA-dev/nbQA/pull/377). Closing this issue.
