### ISSUE TITLE
DOC Add a separate section for list of tools supported by nbqa

### ISSUE THREAD

**Issue by girip11** [nbQA-dev/nbQA#306]
Given the number of tools officially supported(tested) by nbqa is increasing  with every release, should we create a separate section in the documentation to document usage of each tool supported by nbqa with some elaborate examples and recommended setting against each tool.

Suggestions are welcome!

**Comment by s-weigand** [comment]
I think a list of officially supported tools is a great idea.

As for usage documentation, what do you think of notebooks + links to binder?
At least that is how I did it for [flake8-nb](https://flake8-nb.readthedocs.io/en/latest/notebooks/with_out_tags.html) and this way users can directly see what happens if they play with the notebook and the tool.

**Comment by MarcoGorelli** [comment]
these are what appear in the README and docs, so closing for now
