### ISSUE TITLE
Add example / test for autoflake

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#313]
I expect this one to work out-of-the box (for removing unused imports)

**Comment by girip11** [comment]
Shall I take this up?

**Comment by MarcoGorelli** [comment]
Sure, thanks! I've assigned you, but I think you have the permissions to assign yourself - is so, feel free to do so

**Comment by girip11** [comment]
>  I think you have the permissions to assign yourself - is so, feel free to do so

Sure.

**Comment by MarcoGorelli** [comment]
@girip11 I think autoflake would work unreliably if we have a notebook with e.g.

```python
# cell1
import pandas as pd

# cell2
%time pd.DataFrame()
```

where something is imported but is only used after an in-line magic.

An idea would be to raise an error if a notebook contains code after an inline magic and the user runs `nbqa autoflake`, advising them to instead run `nbqa flake8` and remove unused imports manually.

For `nbqa flake8` we can actually just replace `%time <code>` with `<code>` seeing as there's no need to reconstruct the notebook.

I can't think of a way to universally replace `%time <code>` with `<code>` in such a way that formatters will work without issue. All I can think of is to divide tools into linters (which don't modify notebooks) and formatters (which may modify notebooks), and for the former we replace  `%time <code>` with `<code>` and for the latter we replace  `%time <code>` with `type(hash) # <code> etc.` (as we currently do). Thoughts?

**Comment by girip11** [comment]
I had come up with the following approach to fix issue #279. If I am able to fix that, the issue that you discussed above would be handled too.

## Approach

1.  Check if the current line is a line magic. If yes, check if the line magic contains a python code. This check is required because we could have something like `%time func()` or `%load_ext <ext_name>` etc.
2. In cases where the line magic does not contain a python code, we can use existing replacement statement which is `type(token)  # magic token`
3. In cases like line magics with python code (ex: `%time func()`), extract only the code and insert the code into the following template. This replacement code will be a multi line code. But since we use regex match in the latest code, we should be able to match across multiple lines.
```Python
# token or hash - both refer to the same thing
if int(token):
    <extracted_code> # token
```
Above code template would work with both linters and formatters. Formatters would format only `<extracted_code>` and our regex match would still work since we have fixed prefix(`if int(token):`) and fixed suffix(`# token`).

4. In case of linters nothing needs to be done further. 
5. But in case of formatters if we have mutation, during replacement of formatted source code, we can extract the formatted code from the template and reconstruct the magic. For example consider the line magic `%time pd.DataFrame(2d_arr,columns = columns)`. When writing to temp python file, this statement would become 
```Python
if int(token):
    pd.DataFrame(2d_arr,columns = columns) # token
```
After formatting the code would become (note the spaces around the arguments passed to `DataFrame`) like below in the temp python file.

```Python
if int(token):
    pd.DataFrame(2d_arr, columns=columns) # token
```

Now we can extract only `pd.DataFrame(2d_arr, columns=columns)` from the above code and put it in to `%time pd.DataFrame(2d_arr, columns=columns)`. This way the code would not be modified/formatted every time when a formatter like black runs.
6. Handling indentation.Suppose we have the scenario as mentioned in #279

```Python
from foo import func

if True:
    %time func()
```

Then the temp python file would look like 
```Python
from foo import func

if True:
    # notice indentation will happen to the code that we replace
    # currently this logic is done of single line
    # we have to handle this in scenarios where we introduce multiple lines.
    if int(token):
        pd.DataFrame(2d_arr, columns=columns) # token
```

@MarcoGorelli: I have just completed my approach. I have not thought about any corner cases or none didnt come to my mind till now. Please feel free to see if this would break under certain input.

**Comment by MarcoGorelli** [comment]
Wow, I really would not have thought of that on my own, or at least, not in a long time! I can't think of any breakage scenarios, and yes, this seems like it would work as a general solution. Really clever!

Am looking forward to a PR then, this looks like it's going to be amazing!

**Comment by girip11** [comment]
> Wow, I really would not have thought of that on my own, or at least, not in a long time!

Thanks for the kind words. I spent a lot of time(actually days) thinking about this when I was working on the PR that replaced `pass` with `type`(I didnt want to rethink/rewrite that logic sooner for some other scenario). One of the reasons I used regex was to have a flexibility to match multiple lines. It took quite sometime for me to arrive at that multi line approach, because I was not sure how I will be able to match multiple lines. That's when the idea of having a fixed prefix and suffix helped. 

BTW if you had'nt filed #279 at that time, I would have never thought of this approach.

> Am looking forward to a PR then, this looks like it's going to be amazing!

I will work on this PR this week.
