### ISSUE TITLE
FEAT: hook to run notebooks

### ISSUE THREAD

**Issue by pylang** [nbQA-dev/nbQA#438]
## Request

A pre-commit hook that ensures notebooks have valid code and will [run without error][0].

## Motivation

We may push notebooks to remote repos and later discover that users experience errors caused from typos or insufficient kernels/python versions.  Using a pre-push hook to defensively "validate" notebooks can guard again simple errors and reduce calls to CI.

## Approaches

There may be some approaches to this:

1. use [nbconvert to run all notebooks][1]
1. parse the ast based on the notebook's kernel (potentially faster)

## Examples

Pre-commit hook

```yaml
repos:
-     repo:  https://github.com/nbQA-dev/nbQA/issues/new
      rev: <latest>
      hooks:
      - id: nbqa-valid-nb
```
  [0]: https://stackoverflow.com/questions/35471894/can-i-run-jupyter-notebook-cells-in-commandline
  [1]: https://stackoverflow.com/a/40311709/4531270

**Comment by MarcoGorelli** [comment]
Hi @pylang 

Thanks for the idea! I think it would be good to make a notebook equivalent of the pre-commit hook check-ast https://github.com/pre-commit/pre-commit-hooks#check-ast

À pull request would be welcome, if you'd like to submit one, else one of us will probably get round to it within the next month

**Comment by MarcoGorelli** [comment]
@all-contributors please add @pylang for ideas

**Comment by s-weigand** [comment]
The general ensuring that notebooks aren't broken sounds like a use case of [`nbval`](https://github.com/computationalmodelling/nbval) especially using the lax version (`py.test --nbval-lax`).

**Comment by MarcoGorelli** [comment]
Yes, or just [running nbconvert with the --execute flag](https://nbconvert.readthedocs.io/en/latest/execute_api.html) - neither of these options would need to live inside nbqa.

I just tried doing
```
pip install pre-commit-hooks
```
and then
```
nbqa check-ast notebook.ipynb
```
but it says that `check-ast` isn't installed (because, indeed, the module is `pre-commit-hooks`, and `check-ast` is just an entry-point). So...maybe you were right, we should just run the third-party tool directly (rathern than as a Python module) - we'll have to make a special case for doctest, but that's OK.

**Comment by girip11** [comment]
Why not use `py_compile` and `compileall` modules from standard library. It is very similar to doctest.  Since nbqa can run doctest, it should be able to run these modules as well.

I tried the following and it works out of the box. Notice in the input notebook `abspath("."` closing paranthesis is missing.

```Bash
nbqa py_compile tests/data/notebook_for_autoflake.ipynb
```

Input
=======
![image](https://user-images.githubusercontent.com/5471162/98802427-53a52600-2439-11eb-8602-55e8d7d20116.png)

Output
========
Notice the file names are replaced as expected.
![image](https://user-images.githubusercontent.com/5471162/98802540-73d4e500-2439-11eb-9e72-595759899cae.png)


If we need to run on directories, then we can use `compileall` module from python standard library. These modules might generate the .pyc files in the temporary directory. But that should be ok, since the temporary python file directory structure is deleted anyways.

We can create nbqa hooks similar to doctest

**Comment by MarcoGorelli** [comment]
Thanks @girip11 - I wasn't aware of `pycompile`, so I made a PR showing that it's pretty easy to run `check-ast` from `pre-commit-hooks`. I'll look into their difference

> we should just run the third-party tool directly (rathern than as a Python module) 

Actually, there's no need to this, we can just run `pre_commit_hooks.check-_ast`

**Comment by girip11** [comment]
I agree with you on running notebooks with nbconvert execute.

Precommit hook using `check-ast` also looks good. I am fine with using py_compile or check-ast

**Comment by MarcoGorelli** [comment]
@pylang this'll be in the next release, but in the meantime, you can use it as
```
repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 036332e96865994060159ac30d16dd5cdf29cc16  # this will be 0.5.0 in the future
  hooks:
   - id: nbqa-check-ast
     additional_dependencies: [pre-commit-hooks==3.3.0]
```
if you like - please do let us know if you run into any issues

**Comment by pylang** [comment]
I'm stunned.  Fastest, most helpful response on GitHub I've experienced yet.   Wow.  Thank you all.
