### ISSUE TITLE
nbqa and cspell

### ISSUE THREAD

**Issue by dnoliver** [nbQA-dev/nbQA#738]
Hi! 

I am trying to get nbqa and [cspell](https://cspell.org/) working together. 
Got some mild success, but run into two cumbersome situations that I would like to let you know.

This is how I am running it. So far is good, it is great that I have an specific report of which cell is failing, and I could apply different configurations for markdown and for code cells.

```
# For every notebook in the folder
find . -name '*.ipynb' -exec nbqa --nbqa-shell --nbqa-md cspell {} \;
find . -name '*.ipynb' -exec nbqa --nbqa-shell cspell {} \;

# For a single notebook
nbqa --nbqa-shell --nbqa-md cspell notebook.ipynb
nbqa --nbqa-shell cspell notebook.ipynb
```

**Can't execute a cspell subcommand**

Any hints on how to make the commands below to work?

```
root@c77040892c65:~/# cspell --help 
Usage: cspell [options] [command]

Spelling Checker for Code

Options:
  -V, --version                         output the version number
  -h, --help                            display help for command

Commands:
  lint [options] [globs...]             Check spelling
  trace [options] [words...]            Trace words -- Search for words in the configuration and dictionaries.
  check [options] <files...>            Spell check file(s) and display the result. The full file is displayed in color.
  link                                  Link dictionaries and other settings to the cspell global config.
  suggestions|sug [options] [words...]  Spelling Suggestions for words.
  help [command]                        display help for command


root@c77040892c65:~/# nbqa --nbqa-shell --nbqa-md cspell lint notebook.ipynb
No such file or directory: lint

root@c77040892c65:~/# nbqa --nbqa-shell --nbqa-md cspell check notebook.ipynb
No such file or directory: check
```

**Can't control the comments that nbqa add as separators**

Those separators are autogenerated, and gets flagged by `cspell` as unknown words.
Not a big deal, I think I can ignore them with a config file. 
The other option I have is to dump the md content into a file, sed away those separators, and cspell the result, but I will loose the cell index error reporting.

Any ideas how to get them skipped?

```
root@c77040892c65:~/# nbqa --nbqa-shell --nbqa-md cspell  notebook.ipynb
notebook.ipynb:cell_1:0:5 - Unknown word (NBQA)
notebook.ipynb:cell_2:0:5 - Unknown word (NBQA)

root@c77040892c65:~/# nbqa --nbqa-shell --nbqa-md cat notebook.ipynb
# %%NBQA-MD-SEP42abbe
<a id="top"></a>
# Notebook Title
# %%NBQA-MD-SEP42abbe
```

Thank you!

**Comment by MarcoGorelli** [comment]
Hey, 

Thanks for the report

Does

```

nbqa --nbqa-shell --nbqa-md 'cspell lint' notebook.ipynb
```
work? Haven't tried it yet as I'm on my phone

**Comment by dnoliver** [comment]
Not working

```bash
# nbqa --nbqa-shell --nbqa-md 'cspell lint' notebook.ipynb 
Traceback (most recent call last):
  File "/usr/local/bin/nbqa", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/nbqa/__main__.py", line 738, in main
    _check_command_is_installed(cli_args.command, shell=configs["shell"])
  File "/usr/local/lib/python3.8/dist-packages/nbqa/__main__.py", line 701, in _check_command_is_installed
    raise CommandNotFoundError(command)
nbqa.__main__.CommandNotFoundError: nbqa was unable to find cspell lint.
```

**Comment by MarcoGorelli** [comment]
OK, thanks, taking a look (though first need to figure out how to install cspell :smile: )

**Comment by dnoliver** [comment]
This is my Dockerfile, hope it helps

```
FROM ubuntu:20.04

RUN apt-get update \
    && apt-get install -y \
        python3 python3-pip

RUN pip install nbqa black isort mdformat pyupgrade pylint

RUN apt-get update \
    && apt-get install -y curl \
    && curl -fsSL https://deb.nodesource.com/setup_14.x | bash - \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        nodejs

RUN npm install -g cspell

VOLUME /root

WORKDIR /root

CMD bash
```

**Comment by s-weigand** [comment]
I guess for shell aliases to work the `subprocess.run` would need to be run with `shell=True`.
https://github.com/nbQA-dev/nbQA/blob/ed6b5a95ec56fd7e10b6fc64ca6e6d8e39392705/nbqa/__main__.py#L280-L285

As for using `'cspell check'`, my guess is that this is an issue with using lists with `subprocess.run` where one member of the strings in the list contains a space.

If that is the case changing
https://github.com/nbQA-dev/nbQA/blob/ed6b5a95ec56fd7e10b6fc64ca6e6d8e39392705/nbqa/__main__.py#L274-L275
into
```python
    if shell:
        cmd = command.split()
```
should do the trick.

I don't even wanna start counting how often I was sitting there trying to figure out how to get `subprocess.run` to do what I want it to do 😅
Note on this, if you use `shell=True` always pass a string instead of a list!

**Comment by MarcoGorelli** [comment]
The fundamental issue here is that positional arguments can't be passed to nbQA. If it was
```
nbqa cspell --lint
```
then there'd be no issue

So, potential solutions:
- API change: run e.g. `nbqa --nbqa-tool cspell lint --nbqa-files file1.ipynb file2.ipynb`
- add an extra argument to pass positional arguments to the tool, like `nbqa cspell file1.ipynb file2.ipynb --nbqa-posargs lint`
- do some `split` like above

If I could go back in time, I think I'd choose a different API, like the one at the top. But (to my surprise), [it seems like there's a fair few people who use nbQA](https://pypistats.org/packages/nbqa), and an API change would be disruptive

Tempted to go with a `split()` solution then, and there's should be any need to use `shell=True`

**Comment by MarcoGorelli** [comment]
This is a generic argument BTW, if this is supported for `--nbqa-shell`, it should also be supported for Python modules, where I don't think it'll currently work (all tools tests so far take keyword flags)

**Comment by s-weigand** [comment]
@MarcoGorelli I [implemented support for subcommands](https://github.com/s-weigand/nbQA/commit/f952893c4e5371d21bbcb9a606669fc4a3e3e8cd) such as `cspell lint`.

Now here comes the tricky part about testing: 
Python tools like `flakeheaven` (`nbqa "flakeheaven lint" tests/data` or `nbqa "flakeheaven lint" tests/data --nbqa-shell`) work out of the box since python can resolve the path.
But tools like `cspell` need to be called with the abs path to their executable (`which(cspell)`) to work on windows.

This means that for local testing contributors are required to have a tool like this installed or they might break functionality.
A workaround would be to check if `cspell` (I guess it is a nice test case) is installed, skip the test if it is not and ensure the test is run on the CI.

**Comment by MarcoGorelli** [comment]
nice, thanks @s-weigand !

Any thoughts on changing the API? Too disruptive at this stage?

**Comment by s-weigand** [comment]
I think people are already used to encapsulating commands with spaces in a string by other tools (pretty much all installed software one windows 🤣) so this usage should feel quite natural. Especially since `nbqa` is a wrapper tool to run other tools.

Due to the nature of subcommands (commands with different functionality but part of a toolbox e.g. `git add` vs. `git commit`) IHMO it should not be split up for clarity's sake. As for `--nbqa-files` I can imagine that this would cause many users issues when they change the args in their `.pre-commit-config.yaml` and don't have it as the last arg.

Besides files I also can't think of positional args which aren't subcommands (just looks like positional) 😅

What are your thoughts on using `cspell` as unittest case with `@pytest.mark.skip(which(cspell) is None, reason="cspell is not installed")`?

**Comment by MarcoGorelli** [comment]
Hey @s-weigand - just had a chance to look at https://github.com/s-weigand/nbQA/commit/f952893c4e5371d21bbcb9a606669fc4a3e3e8cd , and I think it looks good!

> What are your thoughts on using cspell as unittest case with @pytest.mark.skip(which(cspell) is None, reason="cspell is not installed")?

Yeah no objections!

**Comment by MarcoGorelli** [comment]
Did you want to raise a PR with your commit?

**Comment by MarcoGorelli** [comment]
@all-contributors please add @dnoliver for bugs
