### ISSUE TITLE
Question: Kaggle kernels or Google Colab notebooks?

### ISSUE THREAD

**Issue by neomatrix369** [nbQA-dev/nbQA#84]
Great tool, look forward to using it and apply to my notebooks on https://github.com/neomatrix369/awesome-ai-ml-dl.

How would one run this on Kaggle Kernels or Google Colab notebooks? Can it be run from inside the notebook on the notebook? Or maybe we could use it via a Utility Script on Kaggle.

Would love to know? As this would open up a whole world of possibilities.

**Comment by MarcoGorelli** [comment]
Hey, thanks for the question! I've been field-testing this with some Kaggle notebooks myself, will update with a guide in due course

**Comment by MarcoGorelli** [comment]
I've added some notebooks to Kaggle, e.g. this one https://www.kaggle.com/marcogorelli/cln-titanic-data-science-solutions, which demos running some nbqa checks

Due to the nature of Kaggle notebooks, I don't think it's possible to do this on a running notebook, it looks like you need to download it, run nbqa locally, and then re-upload it.

Anyway, thanks for encouraging this idea, maybe with this being on Kaggle it'll spread more easily :smile:

**Comment by lcrmorin** [comment]
Any update regarding this ? I have started to link my kaggle notebooks with github. I was wondering if there is a way to use this wihin kaggle or when submitting ? (I have opened [a discussion](https://www.kaggle.com/discussions/product-feedback/407807) regarding this on Kaggle)

**Comment by MarcoGorelli** [comment]
hey - I'd suggest downloading the notebook, running whichever tool you want on it, and reuploading. with the kaggle cli, this is quite easy
